// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL4bFdcynOFl0XvwP-mbgT9ifXeYfehy4',
    appId: '1:797899066900:web:8cab7ae957c9df9dc06101',
    messagingSenderId: '797899066900',
    projectId: 'studyflow-5a349',
    authDomain: 'studyflow-5a349.firebaseapp.com',
    storageBucket: 'studyflow-5a349.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyBbAJwd1cXvGvnKmij-4hFyreFpLZko',
    appId: '1:797899066900:android:1fdea7aa2e3bf633c06101',
    messagingSenderId: '797899066900',
    projectId: 'studyflow-5a349',
    storageBucket: 'studyflow-5a349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuL09p2LxntOOV0ckefFApBsewpIO3T9U',
    appId: '1:797899066900:ios:1a21430e0b964271c06101',
    messagingSenderId: '797899066900',
    projectId: 'studyflow-5a349',
    storageBucket: 'studyflow-5a349.firebasestorage.app',
    iosBundleId: 'com.example.studyflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuL09p2LxntOOV0ckefFApBsewpIO3T9U',
    appId: '1:797899066900:ios:1a21430e0b964271c06101',
    messagingSenderId: '797899066900',
    projectId: 'studyflow-5a349',
    storageBucket: 'studyflow-5a349.firebasestorage.app',
    iosBundleId: 'com.example.studyflow',
  );
}
